// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/flytrap/telegram-bot/internal/repositories"
	"github.com/flytrap/telegram-bot/internal/services"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, error) {
	bot, err := InitBot()
	if err != nil {
		return nil, err
	}
	db, err := InitGormDB()
	if err != nil {
		return nil, err
	}
	dataInfoRepository := repositories.NewDataInfoRepository(db)
	dataTagRepository := repositories.NewDataTagRepository(db)
	dataTagService := services.NewDataTagService(dataTagRepository)
	categoryRepository := repositories.NewCategoryRepository(db)
	categoryService := services.NewCategoryService(categoryRepository)
	dataService := services.NewDataService(dataInfoRepository, dataTagService, categoryService)
	coreClient, err := InitStore()
	if err != nil {
		return nil, err
	}
	indexMangerService := services.NewIndexMangerService(coreClient, dataService)
	botManager := services.NewBotManager(dataService, indexMangerService, bot)
	tgBotServiceServer := services.NewTgBotService(dataService)
	grpcServer := InitGrpcServer(tgBotServiceServer)
	injector := &Injector{
		Bot:          bot,
		BotManager:   botManager,
		IndexManager: indexMangerService,
		GrpcServer:   grpcServer,
	}
	return injector, nil
}
