// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/flytrap/telegram-bot/internal/repositories"
	"github.com/flytrap/telegram-bot/internal/services"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, error) {
	bot, err := InitBot()
	if err != nil {
		return nil, err
	}
	db, err := InitGormDB()
	if err != nil {
		return nil, err
	}
	groupRepository := repositories.NewGroupRepository(db)
	tagRepository := repositories.NewTagRepository(db)
	tagService := services.NewTagService(tagRepository)
	categoryRepository := repositories.NewCategoryRepository(db)
	categoryService := services.NewCategoryService(categoryRepository)
	groupService := services.NewGroupService(groupRepository, tagService, categoryService)
	coreClient, err := InitStore()
	if err != nil {
		return nil, err
	}
	indexMangerService := services.NewIndexMangerService(coreClient, groupService)
	botManager := services.NewBotManager(groupService, indexMangerService, bot)
	tgBotServiceServer := services.NewTgBotService(groupService)
	grpcServer := InitGrpcServer(tgBotServiceServer)
	injector := &Injector{
		Bot:          bot,
		BotManager:   botManager,
		IndexManager: indexMangerService,
		GrpcServer:   grpcServer,
	}
	return injector, nil
}
