name: tg bot Docker Image CI

on:
  push:
    tags:
      - v*
env:
  APP_NAME: hidden/telegram-bot #这是您的镜像名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          # 是否 docker push
          push: true
          platforms: |
            darwin/amd64
            windows/amd64
            darwin/arm64
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64
          # docker build arg, 注入 APP_NAME/APP_VERSION
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          # 生成两个 docker tag: ${APP_VERSION} 和 latest
          tags: |
            ${{ env.APP_NAME }}:latest
            ${{ env.APP_NAME }}:${{ env.APP_VERSION }}
