name: Docker Image CI

on:
  push:
    tags:
      - v*
env:
  IMAGE_NAME: hidden/telegram-bot #这是您的镜像名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate App Version
      run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }} .
    - name: Login to Registry
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Image
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}
